### ISSUE TITLE
Missing Prefab on scene examples on latest 

### ISSUE THREAD

**Issue by artigee** [Unity-Technologies/animation-jobs-samples#12]
Missing Prefab on scene examples on latest when it opened from unity 2018.2

**Comment by artigee** [comment]
Test on 2018.3.0b1 seems to be working correct. Nested prefab might be the issue on backward compatibility

**Comment by romainf-unity** [comment]
Thanks for reporting the bug, I've reverted the commit that created it, now it works as expected on 2018.2.

Fixed with commit 72595aec7d3c6721a6b2711302a06b93a5ac84d4
