### ISSUE TITLE
Arms stretching

### ISSUE THREAD

**Issue by KospY** [Unity-Technologies/animation-jobs-samples#9]
If the head effector is implemented, an option to stretch the arm instead of pulling the body (when the hand effector is too far) would be necessary for VR.
See my post for more information: https://forum.unity.com/threads/animation-c-jobs-in-2018-2a5.525012/page-3#post-3695041

**Comment by romainf-unity** [comment]
Hello!

You can change the [`defaultEffectorPullWeight`](https://github.com/Unity-Technologies/animation-jobs-samples/blob/master/Assets/animation-jobs-samples/Samples/Scripts/FullBodyIK/FullBodyIK.cs#L23) to change this behaviour. A pull weight of 1.0 will pull the body entirely, while a pull weight of 0.0 will only stretch the arm.

**Comment by KospY** [comment]
I will try to be more precise sorry!
The idea is to stretch the arm / forearm beyond the normal limit, without scaling them (because it will cause too much deformation). This is done by offsetting/extending bone positions (hand, upper and lower arm). It's needed for VR to correctly adapt the arm length to the player (arms length are not exactly the same between people of the same height). It's something pretty important for VR game featuring body awareness (because pulling body is not possible at it will move the head).
Hope you understand what I mean :)

**Comment by romainf-unity** [comment]
Hello!
I think I understand ;)
The thing is that your VR character rigs seems to need specific constrains that can't work with the default Humanoid characters constraints.
Maybe you'd be able to add some custom Animation Jobs in your PlayableGraph, so that it will perfectly fit your needs.

**Comment by romainf-unity** [comment]
Closed as wont' fix: unfortunately, this is not an issue with the samples themselves, it's a new feature.
